package com.example.telegrambotelena.BotStageEnum;

public enum BotStage {
    IDLE,
    WAITING_EMAIL,
    WAITING_NAME,
    WAITING_SURNAME,
    WAITING_SURNAME_PREVIOUS,
    WAITING_SURNAME_MAIDEN,
    WAITING_DATE_OF_BIRTH,
    WAITING_FATHERS_NAME,
    WAITING_MOTHERS_NAME,
    WAITING_MOTHERS_SURNAME_MAIDEN,
    WAITING_MARITAL_STATUS,
    WAITING_CITY_OF_BIRTH,

    WAITING_NATIONALITY,
    WAITING_CITIZENSHIP,
    WAITING_COUNTRY_OF_BIRTH,
    WAITING_HEIGHT,
    WAITING_PESEL,
    WAITING_EDUCATION,
    WAITING_EYE_COLOUR,

    // Адрес проживания
    WAITING_CITY_OF_RESIDENCE,
    WAITING_STREET_OF_RESIDENCE,
    WAITING_HOUSE_NUMBER,
    WAITING_FLAT_NUMBER,
    WAITING_POSTCODE,

    // Контакты и документы
    WAITING_TELEPHONE,
    WAITING_LAST_ARRIVAL_DATE,
    WAITING_PASSPORT_NUMBER,
    WAITING_RESIDENCE_CARD,
    WAITING_RESIDENCE_CARD_EXPIRE_DATE
}
